version: "3.5"

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_volume: