// <auto-generated />
using BusStopViewer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusStopViewer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221205192552_UserStops")]
    partial class UserStops
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BusStopViewer.Api.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusStopViewer.Api.Data.UserStop", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("StopId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "StopId");

                    b.ToTable("UserStops");
                });

            modelBuilder.Entity("BusStopViewer.Api.Data.UserStop", b =>
                {
                    b.HasOne("BusStopViewer.Api.Data.User", "User")
                        .WithMany("UserStops")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusStopViewer.Api.Data.User", b =>
                {
                    b.Navigation("UserStops");
                });
#pragma warning restore 612, 618
        }
    }
}
